apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      imagePullSecrets:
        - name: docker-ligin
      containers:
        - name: flask-task
          image: ajay365/my-app:3
          ports:
            - containerPort: 5000