apiVersion: v1
kind: Service
metadata:
  name: flask-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    component: web
  ports:
    - port: 5000
      targetPort: 5000
      # NodePort: 30000